AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ENV:
      Type: String
      Default: dev
  LogLevel:
      Type: String
      Default: trace
  SecretName:
      Type: String
      Default: Secret_lambda

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - arm64
    CodeUri: ./src/
    Environment:
      Variables:
        ENV: !Ref ENV
        LOG_LEVEL: !Ref LogLevel
        SECRET_NAME: !Ref SecretName

Resources:
  GenericToolsDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "generic-lambdas-dependencies-${ENV}"
      Description: Dependencies layer for generic-lambdas Lambda functions
      ContentUri: ./dependencies/
      CompatibleRuntimes:
        - nodejs20.x
      CompatibleArchitectures:
        - arm64

  syncQuotaSAPLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/generic-lambdas-${ENV}-syncQuotaSAP"
      RetentionInDays: 90

  syncQuotaSAP:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "generic-lambdas-${ENV}-syncQuotaSAP"
      Handler: handlers/syncQuotaSAP.syncQuotaSAP
      Timeout: 900
      Layers:
        - !Ref GenericToolsDependenciesLayer
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
            Input: '{}'
            Enabled: true
    

